name: BE_DEV_CI

on:
  pull_request:
    branches: 'main'
    paths: 'BE/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build and Push
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
          docker build -t yeim/nest-test ./BE/
          docker run yeim/nest-test npm test