name: BE_DEV_CI

on:
  push:
    branches: 'BE/*'
  pull_request:
    branches: 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
      - run: docker build -t yeim/nest-test ./
      - run: docker run -e CI=true yeim/nest-test npm test